<a href="https://colab.research.google.com/github/OisinStapleton/ml-campus_data-project-colab/blob/main/MiniProjectOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Campus Dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
from IPython.display import display, Markdown # Makes text bold

#Load the Dataset

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/CampusWalkDataset_TemplateIDs(Sheet1).csv',
skiprows=4
)

#Inspect the dataset structure

In [ ]:
print('The shape (rows x cols) of my dataset array\n') #df.info helpful
print(df.shape)
print('\nThe first 5 rows of my dataset: \n')
print(df.head())

The shape (rows x cols) of my dataset array

(994, 27)

The first 5 rows of my dataset:

  recorder_id       date                        location        weather  \
0     R26_001  9/22/2026                L01 MainEntrance  Partly cloudy
1     R26_001  9/22/2026                L02 LibraryGreen          Sunny
2     R26_001  9/22/2026   L06 HedgingBehindSportsCentre  Partly cloudy
3     R26_001  9/22/2026  L08 AccessRoadNearSportsCentre  Partly cloudy
4     R26_001  9/22/2026   L06 HedgingBehindSportsCentre          Sunny

  temperature_c sound level foot_traffic primary_sound_type_urban  \
0            16       Quiet          Low             Human voices
1            16    Moderate          Low                  Traffic
2            16       Quiet          Low             Construction
3            16    Moderate          Low             Human voices
4            16    Moderate          Low                  Traffic

  other_sound_type_urban primary_sound_type_nature  ...    wellbeing_rating  \
0                Traffic                      Wind  ...  Positive wellbeing
1           Human voices                      Wind  ...  Positive wellbeing
2                Traffic                      Wind  ...  Positive wellbeing
3           Human voices                      Wind  ...  Positive wellbeing
4                  Other                      Wind  ...  Positive wellbeing

   ease_rating  stress_rating nature_connection_experience_rating  \
0      Neutral      Stressful                      Less connected
1      Neutral        Neutral             A little more connected
2         Easy    Mostly calm                           No change
3      Neutral        Neutral                 Much more connected
4         Easy    Mostly calm                      Less connected

  most_notable_nature_element other_notes Unnamed: 23 Unnamed: 24 Unnamed: 25  \
0            Plants and trees         NaN         NaN         NaN         NaN
1            Sunrays on grass         NaN         NaN         NaN         NaN
2                  Very quiet         NaN         NaN         NaN         NaN
3                 Harsh wind          NaN         NaN         NaN         NaN
4               Crowded area          NaN         NaN         NaN         NaN

  Unnamed: 26
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN

[5 rows x 27 columns]

# Display Data

In [ ]:
# 1. Adjust Pandas display options for maximum readability
pd.set_option('display.max_columns', None)  # Show all columns without truncation
pd.set_option('display.width', 1000)        # Allow wide rows in the console output

# 2. Read the data while clearly identifying missing values
file_path = '/content/drive/MyDrive/Colab Notebooks/CampusWalkDataset_TemplateIDs(Sheet1).csv'

clean_df = pd.read_csv(
    file_path,
    skiprows=4,              # Skip initial administrative metadata rows
    keep_default_na=True     # Automatically detect standard empty cells as NaN/null
)

# 3. Print a structural overview of the dataset
display(Markdown("**DATASET OVERVIEW**"))
clean_df.info()

# 4. Display the first 5 rows
display(Markdown("**FIRST 5 ROWS**"))
clean_df.info()

**DATASET OVERVIEW**

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Data columns (total 27 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   recorder_id                            199 non-null    object
 1   date                                   135 non-null    object
 2   location                               135 non-null    object
 3   weather                                135 non-null    object
 4   temperature_c                          135 non-null    object
 5   sound level                            135 non-null    object
 6   foot_traffic                           135 non-null    object
 7   primary_sound_type_urban               135 non-null    object
 8   other_sound_type_urban                 132 non-null    object
 9   primary_sound_type_nature              135 non-null    object
 10  other_sound_type_nature                133 non-null    object
 11  insects_count                          135 non-null    float64
 12  birds_count                            135 non-null    float64
 13  trees_presence                         130 non-null    object
 14  native_or_wild_plant_presence          123 non-null    object
 15  ornnamental_or_planted_plant_presence  97 non-null     object
 16  moss_or_lichen_presence                99 non-null     object
 17  wellbeing_rating                       135 non-null    object
 18  ease_rating                            135 non-null    object
 19  stress_rating                          135 non-null    object
 20  nature_connection_experience_rating    135 non-null    object
 21  most_notable_nature_element            120 non-null    object
 22  other_notes                            67 non-null     object
 23  Unnamed: 23                            0 non-null      float64
 24  Unnamed: 24                            0 non-null      float64
 25  Unnamed: 25                            0 non-null      float64
 26  Unnamed: 26                            0 non-null      float64
dtypes: float64(6), object(21)
memory usage: 209.8+ KB

**FIRST 5 ROWS**

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Data columns (total 27 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   recorder_id                            199 non-null    object
 1   date                                   135 non-null    object
 2   location                               135 non-null    object
 3   weather                                135 non-null    object
 4   temperature_c                          135 non-null    object
 5   sound level                            135 non-null    object
 6   foot_traffic                           135 non-null    object
 7   primary_sound_type_urban               135 non-null    object
 8   other_sound_type_urban                 132 non-null    object
 9   primary_sound_type_nature              135 non-null    object
 10  other_sound_type_nature                133 non-null    object
 11  insects_count                          135 non-null    float64
 12  birds_count                            135 non-null    float64
 13  trees_presence                         130 non-null    object
 14  native_or_wild_plant_presence          123 non-null    object
 15  ornnamental_or_planted_plant_presence  97 non-null     object
 16  moss_or_lichen_presence                99 non-null     object
 17  wellbeing_rating                       135 non-null    object
 18  ease_rating                            135 non-null    object
 19  stress_rating                          135 non-null    object
 20  nature_connection_experience_rating    135 non-null    object
 21  most_notable_nature_element            120 non-null    object
 22  other_notes                            67 non-null     object
 23  Unnamed: 23                            0 non-null      float64
 24  Unnamed: 24                            0 non-null      float64
 25  Unnamed: 25                            0 non-null      float64
 26  Unnamed: 26                            0 non-null      float64
dtypes: float64(6), object(21)
memory usage: 209.8+ KB

# Customizing Data to aid reading

In [20]:
from IPython.display import display, HTML
import pandas as pd

# 1. Filter out columns that start with 'Unnamed'
filtered_columns = [col for col in clean_df.columns if not col.startswith('Unnamed:')]
clean_df_filtered = clean_df[filtered_columns].copy()

# 2. Replace NaN/unfilled data with 'Not answered'
clean_df_filtered = clean_df_filtered.fillna('Not answered')

# 3. Handle decimal points: Convert count columns to integer representation if they aren't 'Not answered'
count_cols = ['insects_count', 'birds_count']
for col in count_cols:
    if col in clean_df_filtered.columns:
        clean_df_filtered[col] = clean_df_filtered[col].apply(
            lambda x: int(float(x)) if str(x).replace('.', '', 1).isdigit() else x
        )

# 4. Customizing header displays with color for better readability
display(HTML("<h2 style='color:#1a73e8; font-family:Sans-Serif;'>📊 Filtered Dataset Structure</h2>"))
clean_df_filtered.info()

# 5. Displaying first 5 rows with highlighted columns and styled table
display(HTML("<h2 style='color:#34a853; font-family:Sans-Serif; margin-top:20px;'>🔍 Preview: Cleaned & Custom Filled Data</h2>"))
display(clean_df_filtered.head(5).style.set_properties(**{
    'background-color': '#f8f9fa',
    'border-color': '#dee2e6',
    'color': '#202124'
}).set_table_styles([
    {'selector': 'th', 'props': [('background-color', '#e8f0fe'), ('color', '#1a73e8'), ('font-weight', 'bold')]}
]))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Data columns (total 23 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   recorder_id                            994 non-null    object
 1   date                                   994 non-null    object
 2   location                               994 non-null    object
 3   weather                                994 non-null    object
 4   temperature_c                          994 non-null    object
 5   sound level                            994 non-null    object
 6   foot_traffic                           994 non-null    object
 7   primary_sound_type_urban               994 non-null    object
 8   other_sound_type_urban                 994 non-null    object
 9   primary_sound_type_nature              994 non-null    object
 10  other_sound_type_nature                994 non-null    object
 11  insects_count                          994 non-null    object
 12  birds_count                            994 non-null    object
 13  trees_presence                         994 non-null    object
 14  native_or_wild_plant_presence          994 non-null    object
 15  ornnamental_or_planted_plant_presence  994 non-null    object
 16  moss_or_lichen_presence                994 non-null    object
 17  wellbeing_rating                       994 non-null    object
 18  ease_rating                            994 non-null    object
 19  stress_rating                          994 non-null    object
 20  nature_connection_experience_rating    994 non-null    object
 21  most_notable_nature_element            994 non-null    object
 22  other_notes                            994 non-null    object
dtypes: object(23)
memory usage: 178.7+ KB

#Mean, Mode, Median

In [21]:
import pandas as pd
from IPython.display import display, HTML

# 1. Identify numerical and categorical columns from our filtered dataset
# Excluding 'Not answered' placeholders when computing actual statistics
numeric_cols = ['insects_count', 'birds_count']

# Re-extract clean numeric series ignoring the 'Not answered' strings for accurate calculations
stats_df = clean_df_filtered.copy()
for col in numeric_cols:
    stats_df[col] = pd.to_numeric(stats_df[col], errors='coerce')

# 2. Calculate Mean, Median, and Mode
summary_stats = []

for col in clean_df_filtered.columns:
    # Mode can be calculated for all columns
    mode_series = clean_df_filtered[col].loc[clean_df_filtered[col] != 'Not answered'].mode()
    col_mode = mode_series.iloc[0] if not mode_series.empty else 'N/A'

    if col in numeric_cols:
        col_mean = stats_df[col].mean()
        col_median = stats_df[col].median()

        # Convert float outputs to integers as requested
        display_mean = int(round(col_mean)) if pd.notnull(col_mean) else 'N/A'
        display_median = int(col_median) if pd.notnull(col_median) else 'N/A'
        display_mode = int(col_mode) if isinstance(col_mode, (int, float)) else col_mode
    else:
        display_mean = 'N/A (Categorical)'
        display_median = 'N/A (Categorical)'
        display_mode = col_mode

    summary_stats.append({
        'Column': col,
        'Mean (Integer)': display_mean,
        'Median (Integer)': display_median,
        'Mode': display_mode
    })

# 3. Create DataFrame and display with clean styling
stats_summary_df = pd.DataFrame(summary_stats)

display(HTML("<h2 style='color:#1a73e8; font-family:Sans-Serif;'>📊 Dataset Statistics: Mean, Median, & Mode</h2>"))
display(stats_summary_df.style.set_properties(**{
    'background-color': '#f8f9fa',
    'border-color': '#dee2e6',
    'color': '#202124'
}).set_table_styles([
    {'selector': 'th', 'props': [('background-color', '#e8f0fe'), ('color', '#1a73e8'), ('font-weight', 'bold')]}
]))